# Generated by Django 4.1.3 on 2023-10-16 17:35

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('league', models.CharField(choices=[('Bundesliga', 'Bundesliga'), ('Champions League', 'Champions League'), ('Europa League', 'Europa League'), ('La Liga', 'La Liga'), ('Ligue 1', 'Ligue 1'), ('Premier League', 'Premier League'), ('Serie A', 'Serie A'), ('World Cup', 'World Cup'), ('Worldwide Jerseys', 'Worldwide Jerseys'), ('B-Jerseys Specials', 'B-Jerseys Specials')], max_length=20, validators=[store.models.validate_league_choices])),
                ('image', models.ImageField(upload_to='clubs/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('2023/24', '2023/24'), ('2022/23', '2022/23'), ('2022', '2022')], max_length=10)),
                ('type', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('third', 'Third')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='products/')),
                ('extra_photos', models.ImageField(blank=True, null=True, upload_to='products/extra-photos/')),
                ('description', models.TextField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.clubs')),
            ],
        ),
    ]
