# Generated by Django 4.1.3 on 2023-10-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_extra_photos_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='favorite_in_league',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
