# Generated by Django 4.1.3 on 2023-10-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_type'),
        ('store', '0009_remove_product_favorite_alter_product_season'),
    ]

    operations = [
    ]
