# Generated by Django 4.1.3 on 2023-10-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_merge_20231020_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('2023-24', '2023-24'), ('2022-23', '2022-23'), ('2022', '2022'), ('2023', '2023')], max_length=10),
        ),
    ]
