# Generated by Django 4.1.3 on 2023-10-27 00:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_club_league_alter_product_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_photos',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=store.models.upload_extra_photos1),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=store.models.upload_photo),
        ),
    ]
