# Generated by Django 4.1.3 on 2023-10-29 02:30

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_extra_photos_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(upload_to=store.models.upload_logo),
        ),
    ]
