# Generated by Django 4.1.3 on 2023-10-29 02:32

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=store.models.upload_logo),
        ),
    ]
