# Generated by Django 4.1.3 on 2023-11-17 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_address_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
